---
  title: "EricBalke_BlaineBrewer_CaseStudy01"
author: "Eric Balke"
date: "February 18th, 2019"
output: html_document
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r CS01_Q1}
library(XML)
library(dplyr)
library(tidyr)
library(stringi)
library(rvest)
library(ggplot2)
library(RCurl)

# 1.	How many breweries are present in each state?

# Put URL address into the beerURL and breweryURL objects
beerURL <- paste0("https://raw.githubusercontent.com/BivinSadler/MSDS-6306-Doing-Data-Science/master/Unit%207/Beers.csv")

beers <- read.csv(beerURL)

breweryURL <- paste0("https://raw.githubusercontent.com/BivinSadler/MSDS-6306-Doing-Data-Science/master/Unit%207/Breweries.csv")

brewery <- read.csv(breweryURL)

# 2.	Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file.

# have to fix this merge before proceeding... EB 2/18
merged_data <- merge(beers, brewery, by.x = "Brewery_id", by.y = "Brew_ID")
head(merged_data)
tail(merged_data)
# fix name collisions
colnames(merged_data)[2] <- c("Beer_Name")
colnames(merged_data)[8] <- c("Brewery_Name")

# 3.	Report the number of NA's in each column.
NAs <- colSums(is.na(merged_data))
NAs

# 4.	Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.
median(merged_data$ABV, na.rm=TRUE)
median(merged_data$IBU, na.rm=TRUE)
hist(merged_data$ABV, xlab = "ABV", main = "Histogram of ABV")
hist(merged_data$IBU, xlab = "IBU", main = "Histogram of IBU")

ABV_med <- setDT(as.data.frame(sapply(c("ABV"), function(i) tapply(merged_data[[i]], merged_data$State, median, na.rm=TRUE))), keep.rownames = "State")[]

IBU_med <- setDT(as.data.frame(sapply(c("IBU"), function(i) tapply(merged_data[[i]], merged_data$State, median, na.rm=TRUE))), keep.rownames = "State")[]

ggplot(ABV_med, aes(x=State, y =ABV)) + geom_bar(stat = "identity") + labs(x="State",y="ABV") + ggtitle("Median ABV by State") + theme(plot.title = element_text(hjust = 0.5)) + theme(axis.text=element_text(size=5))

ggplot(IBU_med, aes(x=State, y =IBU)) + geom_bar(stat = "identity") + labs(x="State",y="IBU") + ggtitle("Median IBU by State") + theme(plot.title = element_text(hjust = 0.5)) + theme(axis.text=element_text(size=5))

# 5.	Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?

# 6.	Summary statistics for the ABV variable.

# 7.	Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.

```

